### ISSUE TITLE
`sequentialDVI`: check-problem. Add seed, mutation

### ISSUE THREAD

**Issue by thoree** [thoree/dvir#25]
Fra/til Thore: Sjekk sequentialDVI. Legge til seed slik at resultater blir reproduserbare?
Hvordan håndteres mutasjoner?
``` r
library(dvir)
data(planecrash)
pm = planecrash$pm
am = planecrash$am
missing = planecrash$missing
sequentialDVI(pm, am, missing)
#> Error in checkDVI(pm, am, missing = missing, moves = moves): Third vector must a vector with names of missing persons
```

<sup>Created on 2021-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
Generelt tror jeg `checkDVI()` fortjener en gjennomgang. Noen sjekker er unødvendige, mens andre mangler. Spesielt kan man vurdere om den skal kontrollere at markør-attributter er identiske mellom AM og PM.

**Comment by thoree** [comment]
Enig, jeg skal se på checkDVI senere

**Comment by thoree** [comment]
Problem med sequentialDVI ikke knyttet til `checkDVI`, feilmelding fra `nMarkers()`:
``` r
library(dvir)
pm = example2$pm
am = example2$am
missing = example2$missing
sequentialDVI(pm, am, missing, check = F, verbose = T)
#> Iteration 1 
#>    M1 M2 M3
#> V1  1  0  0
#> V2  1  5  0
#> V3  0  0  5
#> --> V2 = M2
#> Iteration 2 
#>    M1 M3
#> V1 10  0
#> V3  0  5
#> --> V1 = M1
#> Iteration 3 
#>    M3
#> V3  5
#> --> V3 = M3
#> Error: Input to `nMarkers()` must be a `ped` object or a list of such
```

<sup>Created on 2021-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
Ah, I see the problem. I suggest to insert the following line in `singleSearch.R`, just before `### Update the LR matrix`  (line 66):

```r
if(i == length(RES)) 
  break 
```

**Comment by thoree** [comment]
Thanks, problem solved! (I figured out that you meant `in sequentialDVI.R`)

**Comment by magnusdv** [comment]
(Correct - sorry!)
