### ISSUE TITLE
NULL in dviData

### ISSUE THREAD

**Issue by thoree** [thoree/dvir#44]
An error is returned below, maybe this is as it should be ...
``` r
library(dvir)
#> Loading required package: pedtools
dviData(pm = singleton(1), am = NULL, missing = NULL)
#> Error: Input to `nMarkers()` must be a `ped` object or a list of such
```

<sup>Created on 2022-11-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by magnusdv** [comment]
The error message could probably be more informative...I'll push a fix.
