### ISSUE TITLE
No victims left creates problems for jointDVI

### ISSUE THREAD

**Issue by thoree** [thoree/dvir#55]
The only victim is excluded and this creates problems
``` r
library(dvir, quietly =T)

# Attributes of the marker locus
loc = list(name = "L1", alleles = 1:2)

### 1. PM data

pm = list(
  singleton("V1", sex = 1)
  ) |> 
  addMarker(V1 = "2/2",  locusAttr = loc)

### 2. AM data

am = list(
  nuclearPed(father = "R1", mother = "R2",  child = "M1") 
  ) |> 
  addMarker(R1 = "1/1", R2 = "1/1", locusAttr = loc)

### 3. Missing persons
missing = "M1"

### 4. Create DVI object
dvi = dviData(pm = pm, am = am, missing = missing)
excl = findExcluded(dvi, maxInc = 0, verbose = F)
#> 
jointDVI(dvi, pairings = excl$pairings)
#> DVI dataset:
#>  1 victims: V1
#>  1 missing: M1
#>  2 typed refs: R1, R2
#>  1 reference family
#> Error in pairings[[v]]: subscript out of bounds
```

<sup>Created on 2023-02-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by magnusdv** [comment]
Ok, I agree this error message is not too informative. 

It seems reasonable, though, that empty `pairings` should result in an error. Or did you expect a graceful empty return?

**Comment by thoree** [comment]
Thanks, I think we agree on this.
I am, however, a bit uncertain about how to best test for
empty pairings before proceeding with `jointDVI`.

ons. 1. mar. 2023 kl. 07:20 skrev Magnus Dehli Vigeland <
***@***.***>:

**Comment by magnusdv** [comment]
I guess this will be taken care of when `findExcluded` is incorporated in `jointDVI()`. 

For now I'll add a better error message.
