### ISSUE TITLE
`mergePM` omits last sample?

### ISSUE THREAD

**Issue by thoree** [thoree/dvir#61]
It appears that the last sample is omitted 
``` r
library(dvir, quietly = T)
pm1 = singleton("V1") |> 
  addMarker(alleles = 1:3, "V1" = "1/1", name = "L1")
pm2 = singleton("V2") |> 
  addMarker(alleles = 1:3, "V2" = "2/2", name = "L1")

mergePM(list(pm1, pm2))$pmReduced
#> No shared markers
#> $V1
#>  id fid mid sex  L1
#>  V1   *   *   1 1/1
mergePM(list(pm2, pm1))$pmReduced
#> No shared markers
#> $V2
#>  id fid mid sex  L1
#>  V2   *   *   1 2/2
```

<sup>Created on 2023-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by magnusdv** [comment]
Well spotted! A silly bug caused the last individual to potentially drop out. Fixed now.

The curious (and clearly wrong) "No shared markers" was harder to debug. It only manifested in cases with a single marker, and I finally traced it to R's idiosyncratic subsetting rules: If `x` is a matrix, then `x[1, ]` preserves column names only if `x` has at least 2 columns!

Anyway, your example works now, as shown below. (Note the slightly simpler code to build the dataset.)

``` r
library(dvir, quietly = T)

pm = singletons(c("V1", "V2")) |> 
  addMarker(V1 = "1/1", V2 = "2/2", alleles = 1:3, name = "L1")

mergePM(pm)$pmReduced
#> $V1
#>  id fid mid sex  L1
#>  V1   *   *   1 1/1
#> 
#> $V2
#>  id fid mid sex  L1
#>  V2   *   *   1 2/2
```
